import { MainFooter } from "@/components/footer/MainFooter";
import { Navbar } from "@/components/navbar/Navbar";
import { ThemeProviderClient } from "@/components/theme/ThemeProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${geistMono.className} antialiased bg-background`}>
        <ThemeProviderClient>
          <main className="flex flex-col min-h-screen max-w-[1050px] mx-auto p-5 ">
            <Navbar />
            <div className="flex-1 my-10">{children}</div>
            <MainFooter />
          </main>
        </ThemeProviderClient>
      </body>
    </html>
  );
}
